version: '2'
services:
  db.postgres:
    container_name: db.postgres.main
    image: postgres:10
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
